"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from anncsu.common.sdk.utils import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .autprefettura import AutPrefettura, AutPrefetturaTypedDict
    from .provvedimento import Provvedimento, ProvvedimentoTypedDict
    from .richiestaoperazione import (
        Richiesta,
        RichiestaOperazione,
        RichiestaOperazioneTypedDict,
        RichiestaTypedDict,
        TipoOperazione,
    )
    from .rispostaoperazione import (
        Dati,
        DatiTypedDict,
        RispostaOperazione,
        RispostaOperazioneTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .show_statusop import ShowStatusResponse, ShowStatusResponseTypedDict

__all__ = [
    "AutPrefettura",
    "AutPrefetturaTypedDict",
    "Dati",
    "DatiTypedDict",
    "Provvedimento",
    "ProvvedimentoTypedDict",
    "Richiesta",
    "RichiestaOperazione",
    "RichiestaOperazioneTypedDict",
    "RichiestaTypedDict",
    "RispostaOperazione",
    "RispostaOperazioneTypedDict",
    "Security",
    "SecurityTypedDict",
    "ShowStatusResponse",
    "ShowStatusResponseTypedDict",
    "TipoOperazione",
]

_dynamic_imports: dict[str, str] = {
    "AutPrefettura": ".autprefettura",
    "AutPrefetturaTypedDict": ".autprefettura",
    "Provvedimento": ".provvedimento",
    "ProvvedimentoTypedDict": ".provvedimento",
    "Richiesta": ".richiestaoperazione",
    "RichiestaOperazione": ".richiestaoperazione",
    "RichiestaOperazioneTypedDict": ".richiestaoperazione",
    "RichiestaTypedDict": ".richiestaoperazione",
    "TipoOperazione": ".richiestaoperazione",
    "Dati": ".rispostaoperazione",
    "DatiTypedDict": ".rispostaoperazione",
    "RispostaOperazione": ".rispostaoperazione",
    "RispostaOperazioneTypedDict": ".rispostaoperazione",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ShowStatusResponse": ".show_statusop",
    "ShowStatusResponseTypedDict": ".show_statusop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
