"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AutPrefetturaTypedDict(TypedDict):
    data_pref: NotRequired[str]
    r"""Data della prefettura. Obbligatoria se è presente il protocollo_pref"""
    protocollo_pref: NotRequired[str]
    r"""Protocollo della prefettura. Non viene applicato l'uppercase. Obbligatorio se è presente data_pref"""


class AutPrefettura(BaseModel):
    data_pref: Optional[str] = None
    r"""Data della prefettura. Obbligatoria se è presente il protocollo_pref"""

    protocollo_pref: Optional[str] = None
    r"""Protocollo della prefettura. Non viene applicato l'uppercase. Obbligatorio se è presente data_pref"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data_pref", "protocollo_pref"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
