"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .autprefettura import AutPrefettura, AutPrefetturaTypedDict
from .provvedimento import Provvedimento, ProvvedimentoTypedDict
from anncsu.common.sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TipoOperazione(str, Enum):
    r"""Tipo di operazione ('S'=Soppressione, 'I'=Inserimento, 'R'=Aggiornamento)"""

    I = "I"
    R = "R"
    S = "S"


class RichiestaTypedDict(TypedDict):
    codcom: NotRequired[str]
    r"""Codice del comune (obbligatorio)"""
    tipo_operazione: NotRequired[TipoOperazione]
    r"""Tipo di operazione ('S'=Soppressione, 'I'=Inserimento, 'R'=Aggiornamento)"""
    progr_nazionale: NotRequired[str]
    r"""Progressivo nazionale (obbligatorio per soppressione e aggiornamento)"""
    codice_comunale: NotRequired[Nullable[str]]
    r"""Codifica comunale dell'odonimo. Non viene applicato l'uppercase"""
    dug: NotRequired[str]
    r"""DUG (obbligatorio per inserimento e aggiornamento, non ammesso per soppressione, non soggetto a controllo di esistenza nel dizionario)"""
    denom_delibera: NotRequired[str]
    r"""Denominazione Delibera. Viene applicato l'uppercase"""
    denom_in_lingua_1: NotRequired[str]
    r"""Odonimo in lingua, comprensivo della dug, per comuni bi/tri lingue. Viene applicato l'uppercase"""
    denom_in_lingua_2: NotRequired[str]
    r"""Odonimo in ulteriore lingua, comprensivo della dug, per comuni tri lingue. Viene applicato l'uppercase"""
    denom_localita: NotRequired[str]
    r"""Denominazione Località. Viene applicato l'uppercase"""
    provvedimento: NotRequired[ProvvedimentoTypedDict]
    aut_prefettura: NotRequired[AutPrefetturaTypedDict]
    data_valid_amm: NotRequired[str]
    r"""Data di validità amministrativa, minore o uguale della data corrente per inserimento e soppressione. Per aggiornamento anche >= della precedente"""


class Richiesta(BaseModel):
    codcom: Optional[str] = None
    r"""Codice del comune (obbligatorio)"""

    tipo_operazione: Optional[TipoOperazione] = None
    r"""Tipo di operazione ('S'=Soppressione, 'I'=Inserimento, 'R'=Aggiornamento)"""

    progr_nazionale: Optional[str] = None
    r"""Progressivo nazionale (obbligatorio per soppressione e aggiornamento)"""

    codice_comunale: OptionalNullable[str] = UNSET
    r"""Codifica comunale dell'odonimo. Non viene applicato l'uppercase"""

    dug: Optional[str] = None
    r"""DUG (obbligatorio per inserimento e aggiornamento, non ammesso per soppressione, non soggetto a controllo di esistenza nel dizionario)"""

    denom_delibera: Optional[str] = None
    r"""Denominazione Delibera. Viene applicato l'uppercase"""

    denom_in_lingua_1: Optional[str] = None
    r"""Odonimo in lingua, comprensivo della dug, per comuni bi/tri lingue. Viene applicato l'uppercase"""

    denom_in_lingua_2: Optional[str] = None
    r"""Odonimo in ulteriore lingua, comprensivo della dug, per comuni tri lingue. Viene applicato l'uppercase"""

    denom_localita: Optional[str] = None
    r"""Denominazione Località. Viene applicato l'uppercase"""

    provvedimento: Optional[Provvedimento] = None

    aut_prefettura: Optional[AutPrefettura] = None

    data_valid_amm: Optional[str] = None
    r"""Data di validità amministrativa, minore o uguale della data corrente per inserimento e soppressione. Per aggiornamento anche >= della precedente"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "codcom",
                "tipo_operazione",
                "progr_nazionale",
                "codice_comunale",
                "dug",
                "denom_delibera",
                "denom_in_lingua_1",
                "denom_in_lingua_2",
                "denom_localita",
                "provvedimento",
                "aut_prefettura",
                "data_valid_amm",
            ]
        )
        nullable_fields = set(["codice_comunale"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class RichiestaOperazioneTypedDict(TypedDict):
    richiesta: NotRequired[RichiestaTypedDict]


class RichiestaOperazione(BaseModel):
    richiesta: Optional[Richiesta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["richiesta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
