"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DatiTypedDict(TypedDict):
    codcom: NotRequired[str]
    r"""Codice del comune"""
    progr_nazionale: NotRequired[str]
    r"""Progressivo nazionale"""
    codice_comunale: NotRequired[Nullable[str]]
    r"""Codifica comunale dell'odonimo"""
    dug: NotRequired[str]
    r"""DUG (obbligatorio per inserimento e aggiornamento, non ammesso per soppressione)"""
    denom_delibera: NotRequired[str]
    r"""Denominazione Delibera"""
    denom_in_lingua_1: NotRequired[str]
    r"""Odonimo in lingua, comprensivo della dug, per comuni bi/tri lingue. Viene applicato l'uppercase"""
    denom_in_lingua_2: NotRequired[str]
    r"""Odonimo in ulteriore lingua, comprensivo della dug, per comuni tri lingue. Viene applicato l'uppercase"""
    data_inizio: NotRequired[str]
    r"""Data di inizio validità dell'odonimo per l'area di circolazione, identificata dal progressivo nazionale"""
    data_fine: NotRequired[str]
    r"""Data di fine validità dell'odonimo per l'area di circolazione, identificata dal progressivo nazionale"""
    data_ini_valid_amm: NotRequired[Nullable[str]]
    r"""Data di inizio validità amministrativa dell'odonimo"""
    data_fine_valid_amm: NotRequired[Nullable[str]]
    r"""Data di fine validità amministrativa dell'area di circolazione e dell'odonimo"""


class Dati(BaseModel):
    codcom: Optional[str] = None
    r"""Codice del comune"""

    progr_nazionale: Optional[str] = None
    r"""Progressivo nazionale"""

    codice_comunale: OptionalNullable[str] = UNSET
    r"""Codifica comunale dell'odonimo"""

    dug: Optional[str] = None
    r"""DUG (obbligatorio per inserimento e aggiornamento, non ammesso per soppressione)"""

    denom_delibera: Optional[str] = None
    r"""Denominazione Delibera"""

    denom_in_lingua_1: Optional[str] = None
    r"""Odonimo in lingua, comprensivo della dug, per comuni bi/tri lingue. Viene applicato l'uppercase"""

    denom_in_lingua_2: Optional[str] = None
    r"""Odonimo in ulteriore lingua, comprensivo della dug, per comuni tri lingue. Viene applicato l'uppercase"""

    data_inizio: Optional[str] = None
    r"""Data di inizio validità dell'odonimo per l'area di circolazione, identificata dal progressivo nazionale"""

    data_fine: Annotated[Optional[str], pydantic.Field(alias="data_FINE")] = None
    r"""Data di fine validità dell'odonimo per l'area di circolazione, identificata dal progressivo nazionale"""

    data_ini_valid_amm: OptionalNullable[str] = UNSET
    r"""Data di inizio validità amministrativa dell'odonimo"""

    data_fine_valid_amm: OptionalNullable[str] = UNSET
    r"""Data di fine validità amministrativa dell'area di circolazione e dell'odonimo"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "codcom",
                "progr_nazionale",
                "codice_comunale",
                "dug",
                "denom_delibera",
                "denom_in_lingua_1",
                "denom_in_lingua_2",
                "data_inizio",
                "data_FINE",
                "data_ini_valid_amm",
                "data_fine_valid_amm",
            ]
        )
        nullable_fields = set(
            ["codice_comunale", "data_ini_valid_amm", "data_fine_valid_amm"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class RispostaOperazioneTypedDict(TypedDict):
    id_richiesta: NotRequired[str]
    r"""Identificativo assegnato alla richiesta"""
    esito: NotRequired[str]
    r"""Esito dell'operazione"""
    messaggio: NotRequired[str]
    r"""Messaggio associato all'esito"""
    dati: NotRequired[List[DatiTypedDict]]


class RispostaOperazione(BaseModel):
    id_richiesta: Annotated[Optional[str], pydantic.Field(alias="idRichiesta")] = None
    r"""Identificativo assegnato alla richiesta"""

    esito: Optional[str] = None
    r"""Esito dell'operazione"""

    messaggio: Optional[str] = None
    r"""Messaggio associato all'esito"""

    dati: Optional[List[Dati]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["idRichiesta", "esito", "messaggio", "dati"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Dati.model_rebuild()
except NameError:
    pass
try:
    RispostaOperazione.model_rebuild()
except NameError:
    pass
