"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.sdk.types import BaseModel, UNSET_SENTINEL
from anncsu.common.sdk.utils import FieldMetadata, SecurityMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    agid_jwt_signature: NotRequired[str]
    agid_jwt_tracking_evidence: NotRequired[str]


class Security(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                composite=True,
                field_name="Authorization",
            )
        ),
    ] = None

    agid_jwt_signature: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                composite=True,
                field_name="Agid-JWT-Signature",
            )
        ),
    ] = None

    agid_jwt_tracking_evidence: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                composite=True,
                field_name="Agid-JWT-TrackingEvidence",
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["bearerAuth", "Agid-JWT-Signature", "Agid-JWT-TrackingEvidence"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
