"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.errors import AnncsuError
from anncsu.common.sdk.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class ServiceUnavailableErrorData(BaseModel):
    status: Optional[str] = None


@dataclass(unsafe_hash=True)
class ServiceUnavailableError(AnncsuError):
    r"""Il server non è disponibile."""

    data: ServiceUnavailableErrorData = field(hash=False)

    def __init__(
        self,
        data: ServiceUnavailableErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
