workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    ANNCSU Accessi API:
        inputs:
            - location: oas/dev/Specifica API - ANNCSU - Aggiornamento accessi.yaml
        transformations:
            - removeUnused: true
        output: .speakeasy/out.accessi.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-accessi-api
    ANNCSU Coordinate API:
        inputs:
            - location: oas/dev/Specifica API - ANNCSU - Aggiornamento coordinate.yml
        transformations:
            - removeUnused: true
        output: .speakeasy/out.coordinate.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-coordinate-api
    ANNCSU Odonimi API:
        inputs:
            - location: oas/dev/Specifica API - ANNCSU - Aggiornamento odonimi.yaml
        transformations:
            - removeUnused: true
        output: .speakeasy/out.odonimi.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-odonimi-api
    ANNCSU REST API:
        inputs:
            - location: ../oas/dev/Specifica API - ANNCSU – Consultazione per le PA.yaml
        transformations:
            - removeUnused: true
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-rest-api
targets:
    accessi:
        target: python
        source: ANNCSU Accessi API
        output: accessi-sdk
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-accessi-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    anncsu:
        target: python
        source: ANNCSU REST API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-rest-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    coordinate:
        target: python
        source: ANNCSU Coordinate API
        output: coordinate-sdk
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-coordinate-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    odonimi:
        target: python
        source: ANNCSU Odonimi API
        output: odonimi-sdk
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/geobeyond-zd1/anncsu/anncsu-odonimi-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
