"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.sdk.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ElencoodonimiprogPostRequestTypedDict(TypedDict):
    r"""search input data"""

    req: NotRequired[str]
    codcom: NotRequired[str]
    denomparz: NotRequired[str]


class ElencoodonimiprogPostRequest(BaseModel):
    r"""search input data"""

    req: Optional[str] = None

    codcom: Optional[str] = None

    denomparz: Optional[str] = None


class ElencoodonimiprogPostDataTypedDict(TypedDict):
    prognaz: NotRequired[str]
    cododocomunale: NotRequired[str]
    dug: NotRequired[str]
    denomuff: NotRequired[str]
    denomloc: NotRequired[str]
    denomlingua1: NotRequired[str]
    denomlingua2: NotRequired[str]


class ElencoodonimiprogPostData(BaseModel):
    prognaz: Optional[str] = None

    cododocomunale: Optional[str] = None

    dug: Optional[str] = None

    denomuff: Annotated[Optional[str], pydantic.Field(alias="duf")] = None

    denomloc: Optional[str] = None

    denomlingua1: Optional[str] = None

    denomlingua2: Optional[str] = None


class ElencoodonimiprogPostResponseTypedDict(TypedDict):
    r"""Successful operation"""

    res: NotRequired[str]
    data: NotRequired[List[ElencoodonimiprogPostDataTypedDict]]


class ElencoodonimiprogPostResponse(BaseModel):
    r"""Successful operation"""

    res: Optional[str] = None

    data: Optional[List[ElencoodonimiprogPostData]] = None
