"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.sdk.types import BaseModel
from anncsu.common.sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ElencoOdonimiGetPathParamRequestTypedDict(TypedDict):
    codcom: str
    r"""Codice Belfiore del comune dell'odonimo"""
    denomparz: str
    r"""Denominazione anche parziale dell'odonimo - base64 encoded"""


class ElencoOdonimiGetPathParamRequest(BaseModel):
    codcom: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Codice Belfiore del comune dell'odonimo"""

    denomparz: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Denominazione anche parziale dell'odonimo - base64 encoded"""


class ElencoOdonimiGetPathParamDataTypedDict(TypedDict):
    cododocomunale: NotRequired[str]
    dug: NotRequired[str]
    denomuff: NotRequired[str]
    denomloc: NotRequired[str]
    denomlingua1: NotRequired[str]
    denomlingua2: NotRequired[str]


class ElencoOdonimiGetPathParamData(BaseModel):
    cododocomunale: Optional[str] = None

    dug: Optional[str] = None

    denomuff: Annotated[Optional[str], pydantic.Field(alias="duf")] = None

    denomloc: Optional[str] = None

    denomlingua1: Optional[str] = None

    denomlingua2: Optional[str] = None


class ElencoOdonimiGetPathParamResponseTypedDict(TypedDict):
    r"""Successful operation"""

    res: NotRequired[str]
    data: NotRequired[List[ElencoOdonimiGetPathParamDataTypedDict]]


class ElencoOdonimiGetPathParamResponse(BaseModel):
    r"""Successful operation"""

    res: Optional[str] = None

    data: Optional[List[ElencoOdonimiGetPathParamData]] = None
