"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from anncsu.common.sdk.utils import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .richiestaoperazione import (
        Accesso,
        AccessoTypedDict,
        Coordinate,
        CoordinateTypedDict,
        Richiesta,
        RichiestaOperazione,
        RichiestaOperazioneTypedDict,
        RichiestaTypedDict,
    )
    from .rispostaoperazione import (
        Dati,
        DatiTypedDict,
        RispostaOperazione,
        RispostaOperazioneTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .show_statusop import ShowStatusResponse, ShowStatusResponseTypedDict

__all__ = [
    "Accesso",
    "AccessoTypedDict",
    "Coordinate",
    "CoordinateTypedDict",
    "Dati",
    "DatiTypedDict",
    "Richiesta",
    "RichiestaOperazione",
    "RichiestaOperazioneTypedDict",
    "RichiestaTypedDict",
    "RispostaOperazione",
    "RispostaOperazioneTypedDict",
    "Security",
    "SecurityTypedDict",
    "ShowStatusResponse",
    "ShowStatusResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "Accesso": ".richiestaoperazione",
    "AccessoTypedDict": ".richiestaoperazione",
    "Coordinate": ".richiestaoperazione",
    "CoordinateTypedDict": ".richiestaoperazione",
    "Richiesta": ".richiestaoperazione",
    "RichiestaOperazione": ".richiestaoperazione",
    "RichiestaOperazioneTypedDict": ".richiestaoperazione",
    "RichiestaTypedDict": ".richiestaoperazione",
    "Dati": ".rispostaoperazione",
    "DatiTypedDict": ".rispostaoperazione",
    "RispostaOperazione": ".rispostaoperazione",
    "RispostaOperazioneTypedDict": ".rispostaoperazione",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ShowStatusResponse": ".show_statusop",
    "ShowStatusResponseTypedDict": ".show_statusop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
