"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from anncsu.common.sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CoordinateTypedDict(TypedDict):
    x: NotRequired[Nullable[str]]
    r"""Coordinata X, obbligatoria se viene valorizzata Y. (Valori ammessi in Italia 6.0 ≤ x ≤ 18.0)"""
    y: NotRequired[Nullable[str]]
    r"""Coordinata Y, obbligatoria se viene valorizzata X. (Valori ammessi in Italia 36.0 ≤ y ≤ 47.0)"""
    z: NotRequired[Nullable[str]]
    r"""Quota, da non valorizzare in assenza di X e Y, espressa in metri"""
    metodo: NotRequired[Nullable[str]]
    r"""Metodo di rilevazione, da non valorizzare in assenza di X e Y"""


class Coordinate(BaseModel):
    x: OptionalNullable[str] = UNSET
    r"""Coordinata X, obbligatoria se viene valorizzata Y. (Valori ammessi in Italia 6.0 ≤ x ≤ 18.0)"""

    y: OptionalNullable[str] = UNSET
    r"""Coordinata Y, obbligatoria se viene valorizzata X. (Valori ammessi in Italia 36.0 ≤ y ≤ 47.0)"""

    z: OptionalNullable[str] = UNSET
    r"""Quota, da non valorizzare in assenza di X e Y, espressa in metri"""

    metodo: OptionalNullable[str] = UNSET
    r"""Metodo di rilevazione, da non valorizzare in assenza di X e Y"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x", "y", "z", "metodo"])
        nullable_fields = set(["x", "y", "z", "metodo"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class AccessoTypedDict(TypedDict):
    progr_civico: NotRequired[str]
    r"""Progressivo accesso (obbligatorio solo per operazione_civico='R','S')"""
    codice_civico_comunale: NotRequired[Nullable[str]]
    r"""Codifica comunale dell'accesso"""
    numero: NotRequired[Nullable[str]]
    r"""Numero civico, da non valorizzare per operazione_civico='S' o accesso identificato con il sistema metrico"""
    esponente: NotRequired[Nullable[str]]
    r"""Da valorizzare se necessario per identificare l'accesso, solo per tipo_operazione='I','R'"""
    specificita: NotRequired[Nullable[str]]
    r"""da valorizzare se necessario per identificare l'accesso per comuni specifici, solo per tipo_operazione='I','R'"""
    metrico: NotRequired[Nullable[str]]
    r"""metrico, da non valorizzare per operazione_civico='S' o accesso identificato con il numero civico"""
    sezione_censimento: NotRequired[str]
    r"""Sezione di censimento, da valorizzare solo per operazione_civico='I','R'"""
    operazione_civico: NotRequired[str]
    r"""Tipo di operazione sull'accesso. 'I'=inserimento, 'R'=aggiornamento, 'S'=soppressione"""
    coordinate: NotRequired[CoordinateTypedDict]
    data_valid_amm: NotRequired[Nullable[str]]
    r"""Data di validita' amministrativa, se assente è equiparata alla data corrente, per tipo_operazione=S rappresenta la data di fine validita per le altre operazioni la data di inizio"""
    isolato: NotRequired[Nullable[str]]
    r"""Codice isolato, facoltativo, da valorizzare solo per operazione_civico='I','R'"""


class Accesso(BaseModel):
    progr_civico: Optional[str] = None
    r"""Progressivo accesso (obbligatorio solo per operazione_civico='R','S')"""

    codice_civico_comunale: OptionalNullable[str] = UNSET
    r"""Codifica comunale dell'accesso"""

    numero: OptionalNullable[str] = UNSET
    r"""Numero civico, da non valorizzare per operazione_civico='S' o accesso identificato con il sistema metrico"""

    esponente: OptionalNullable[str] = UNSET
    r"""Da valorizzare se necessario per identificare l'accesso, solo per tipo_operazione='I','R'"""

    specificita: OptionalNullable[str] = UNSET
    r"""da valorizzare se necessario per identificare l'accesso per comuni specifici, solo per tipo_operazione='I','R'"""

    metrico: OptionalNullable[str] = UNSET
    r"""metrico, da non valorizzare per operazione_civico='S' o accesso identificato con il numero civico"""

    sezione_censimento: Optional[str] = None
    r"""Sezione di censimento, da valorizzare solo per operazione_civico='I','R'"""

    operazione_civico: Optional[str] = None
    r"""Tipo di operazione sull'accesso. 'I'=inserimento, 'R'=aggiornamento, 'S'=soppressione"""

    coordinate: Optional[Coordinate] = None

    data_valid_amm: OptionalNullable[str] = UNSET
    r"""Data di validita' amministrativa, se assente è equiparata alla data corrente, per tipo_operazione=S rappresenta la data di fine validita per le altre operazioni la data di inizio"""

    isolato: OptionalNullable[str] = UNSET
    r"""Codice isolato, facoltativo, da valorizzare solo per operazione_civico='I','R'"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "progr_civico",
                "codice_civico_comunale",
                "numero",
                "esponente",
                "specificita",
                "metrico",
                "sezione_censimento",
                "operazione_civico",
                "coordinate",
                "data_valid_amm",
                "isolato",
            ]
        )
        nullable_fields = set(
            [
                "codice_civico_comunale",
                "numero",
                "esponente",
                "specificita",
                "metrico",
                "data_valid_amm",
                "isolato",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class RichiestaTypedDict(TypedDict):
    codcom: NotRequired[str]
    r"""Codice del comune (obbligatorio)"""
    progr_nazionale: NotRequired[str]
    r"""Progressivo nazionale (obbligatorio)"""
    accesso: NotRequired[AccessoTypedDict]


class Richiesta(BaseModel):
    codcom: Optional[str] = None
    r"""Codice del comune (obbligatorio)"""

    progr_nazionale: Optional[str] = None
    r"""Progressivo nazionale (obbligatorio)"""

    accesso: Optional[Accesso] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["codcom", "progr_nazionale", "accesso"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RichiestaOperazioneTypedDict(TypedDict):
    richiesta: NotRequired[RichiestaTypedDict]


class RichiestaOperazione(BaseModel):
    richiesta: Optional[Richiesta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["richiesta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
